stages:
  gen:
    matrix:
      stretch: &stretch
        - -0.3
        - -0.1
        - 0.1
        - 0.3
        - 0.5
    cmd: >-
      python src/gen.py
      --stretch ${item.stretch}
      --output data/${item.stretch}/input.vtu
    deps:
      - src/gen.py
    outs:
      - data/${item.stretch}/input.vtu

  sim:
    matrix:
      stretch: *stretch
      model: &model
        - corotated
        - linear
        - neo_hookean_stable
    cmd: >-
      python src/main.py
      --input data/${item.stretch}/input.vtu
      --model ${item.model}
      --output data/${item.stretch}/${item.model}.vtu
    deps:
      - data/${item.stretch}/input.vtu
      - src/main.py
    outs:
      - data/${item.stretch}/${item.model}.vtu

  plot/camera:
    cmd: python src/plot/camera.py --camera plot/camera.json
    deps:
      - data/
      - src/plot/camera.py
    outs:
      - plot/camera.json

  plot/solution:
    matrix:
      stretch: *stretch
      model: *model
    cmd: >-
      python src/plot/solution.py
      --camera plot/camera.json
      --fig plot/${item.stretch}/${item.model}.svg
      --solution data/${item.stretch}/${item.model}.vtu
      --stretch ${item.stretch}
    deps:
      - data/${item.stretch}/${item.model}.vtu
      - plot/camera.json
      - src/plot/solution.py
    outs:
      - plot/${item.stretch}/${item.model}.svg
