name: mesh-kit

channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
  - pytorch3d

dependencies:
  - poetry
  - python=3.11
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch=2.1.0
  - pytorch3d::pytorch3d
