name: mesh-kit

channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
  - pytorch3d

dependencies:
  - python=3.11
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - pytorch3d::pytorch3d
  - pip:
      - icecream
      - loguru
      - matplotlib
      - numpy
      - opencv-python
      - pydantic
      - pymeshfix
      - pyvista[all]
      - rich
      - scipy
      - taichi
      - tetgen
      - tqdm
      - trimesh[all]
      - typer
