version: "3"

tasks:
  setup:
    cmds:
      - micromamba --yes --name "mesh-kit" create --file environment.yaml
      - micromamba --name "mesh-kit" run poetry install
    sources:
      - environment.yaml
      - poetry.lock
