import numpy as np
from jaxtyping import Bool, Float, Integer

B = Bool[np.ndarray, ""]
BN = Bool[np.ndarray, "N"]

F = Float[np.ndarray, ""]
F2 = Float[np.ndarray, "2"]
F3 = Float[np.ndarray, "3"]
F4 = Float[np.ndarray, "4"]
FN = Float[np.ndarray, "N"]
F22 = Float[np.ndarray, "2 2"]
F23 = Float[np.ndarray, "2 3"]
F24 = Float[np.ndarray, "2 4"]
F32 = Float[np.ndarray, "3 2"]
F33 = Float[np.ndarray, "3 3"]
F34 = Float[np.ndarray, "3 4"]
F42 = Float[np.ndarray, "4 2"]
F43 = Float[np.ndarray, "4 3"]
F44 = Float[np.ndarray, "4 4"]
FMN = Float[np.ndarray, "M N"]
FN3 = Float[np.ndarray, "N 3"]
FN6 = Float[np.ndarray, "N 6"]
FNN = Float[np.ndarray, "N N"]
FMN3 = Float[np.ndarray, "M N 3"]

I = Integer[np.ndarray, ""]
I2 = Integer[np.ndarray, "2"]
I3 = Integer[np.ndarray, "3"]
I4 = Integer[np.ndarray, "4"]
IN = Integer[np.ndarray, "N"]
IN2 = Integer[np.ndarray, "N 2"]
IN3 = Integer[np.ndarray, "N 3"]
IN4 = Integer[np.ndarray, "N 4"]
