stages:
  CT-to-mesh/face:
    matrix:
      subject-id: &subject-id
        - 120056
      stage: &stage
        - pre
        - post
    cmd: >-
      python src/CT-to-mesh.py
      --ct data/01_raw/CT/${item.subject-id}/${item.stage}
      --mesh data/02_intermediate/${item.subject-id}/${item.stage}/00-face.ply
      --threshold -200
    deps:
      - data/01_raw/CT/${item.subject-id}/${item.stage}
      - src/CT-to-mesh.py
    outs:
      - data/02_intermediate/${item.subject-id}/${item.stage}/00-face.ply

  CT-to-mesh/skull:
    matrix:
      subject-id: *subject-id
      stage: *stage
    cmd: >-
      python src/CT-to-mesh.py
      --ct data/01_raw/CT/${item.subject-id}/${item.stage}
      --mesh data/02_intermediate/${item.subject-id}/${item.stage}/00-skull.ply
      --threshold 200
    deps:
      - data/01_raw/CT/${item.subject-id}/${item.stage}
      - src/CT-to-mesh.py
    outs:
      - data/02_intermediate/${item.subject-id}/${item.stage}/00-skull.ply
