stages:
  plot/curve:
    cmd: JAX_DEBUG_NANS=False python src/plot/curve.py
    deps:
      - src/plot/curve.py
    outs:
      - plot/curve/energy.svg
      - plot/curve/normal-force.svg
      - plot/curve/shear-force.svg
  plot/tet:
    cmd: python src/plot/tet.py
    deps:
      - src/plot/tet.py
    outs:
      - plot/tet/rest.svg
      - plot/tet/shear.svg
      - plot/tet/squash.svg
      - plot/tet/stretch.svg
