metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
stages:
  rigid:
    cmd: >-
      python src/rigid.py
      --output data/rigid.vtp
      /home/liblaf/.local/opt/Wrap/Gallery/Basemeshes/WrapJaw.obj
    deps:
    - /home/liblaf/.local/opt/Wrap/Gallery/Basemeshes/WrapJaw.obj
    - src/rigid.py
    outs:
    - data/rigid.vtp

  non-rigid:
    cmd: >-
      python src/non-rigid.py
      --output data/non-rigid.vtp
      --source data/rigid.vtp
    deps:
    - data/rigid.vtp
    - src/non-rigid.py
    params:
    - params/non-rigid.yaml:
    outs:
    - data/non-rigid.vtp

  transfer:
    cmd: >-
      python src/transfer.py
      --output data/transfer.vtp
      --source data/non-rigid.vtp
    deps:
    - data/non-rigid.vtp
    - src/transfer.py
    outs:
    - data/transfer.vtp
