version: "3"

vars:
  DATA_DIR: '{{joinPath .HOME "Documents" "CT"}}'

includes:
  backup:
    taskfile: task/backup.yaml
  template:face:
    taskfile: task/template.yaml
    vars:
      COMPONENT: face
  template:skull:
    taskfile: task/template.yaml
    vars:
      COMPONENT: skull
  register:pre:face:
    taskfile: task/register.yaml
    vars:
      COMPONENT: face
      STAGE: pre
  register:pre:skull:
    taskfile: task/register.yaml
    vars:
      COMPONENT: skull
      STAGE: pre
  register:post:face:
    taskfile: task/register.yaml
    vars:
      COMPONENT: face
      STAGE: post
  register:post:skull:
    taskfile: task/register.yaml
    vars:
      COMPONENT: skull
      STAGE: post

tasks:
  default:
    deps:
      - register:pre:face:register

run: once
