version: "3"

vars:
  CMD_DIR: "{{.ROOT_DIR}}/cmd"
  DATA_DIR: "{{.HOME}}/Documents/CT"
  TARGET: 赵颖

includes:
  template:face:
    taskfile: taskfiles/template.yaml
    vars:
      COMPONENT: face
  template:skull:
    taskfile: taskfiles/template.yaml
    vars:
      COMPONENT: skull
  register:pre:face:
    taskfile: taskfiles/register.yaml
    vars:
      STAGE: pre
      COMPONENT: face
  register:pre:skull:
    taskfile: taskfiles/register.yaml
    vars:
      STAGE: pre
      COMPONENT: skull
  register:post:face:
    taskfile: taskfiles/register.yaml
    vars:
      STAGE: post
      COMPONENT: face
  register:post:skull:
    taskfile: taskfiles/register.yaml
    vars:
      STAGE: post
      COMPONENT: skull

tasks:
  default:
    deps:
      - register:pre:face:CT2mesh
