name: Docs

on:
  push:

jobs:
  docs:
    name: Docs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0
      - name: Build
        run: pixi run docs
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site
      - if: github.ref == 'refs/heads/main'
        name: Deploy
        run: pixi run docs-deploy
